# Generated by Django 4.0.2 on 2022-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_account_uuid_token_uploaddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocuments',
            name='Name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='2c1fcbc4-5919-44fb-8600-dc6e61744552', editable=False),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='Language',
            field=models.CharField(choices=[('select', 'select'), ('Benagli', 'Benagli'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu'), ('English', 'English'), ('Other', 'Other')], default='Select', max_length=20),
        ),
    ]
